export const ui: string;
export const checkbox: string;
export const box: string;
export const disabled: string;
export const hidden: string;
export const radio: string;
export const slider: string;
export const toggle: string;
export const fitted: string;
